site_name: FlowEcho Wave Nexus
site_description: 这里是 FlowEcho 门户网站。让每一次呐喊都有回声。
theme:
  name: material
  language: zh
  logo: images/logo-bar.png
  favicon: images/logo-light.png
  custom_dir: overrides
  features:
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    # - navigation.instant
    #- header.autohide  #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy #代码复制
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - navigation.indexes
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: fet-color-light
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: fet-color-dark
      toggle:
        icon: material/weather-sunny
        name: 亮色模式

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html

plugins:
  - glightbox
  - markdownextradata
  - blog:
      blog_dir: blog
      blog_toc: true
      post_date_format: long
      post_url_date_format: yyyy/MM/dd
      post_url_format: "{file}"
      post_excerpt: required
      post_excerpt_separator: <!-- more -->
      archive_name: 归档
      archive_toc: true
      archive_date_format: MMMM yyyy
      archive_url_date_format: yyyy/MM
      archive_url_format: "archive/{date}"
      categories_name: 标签
      categories_toc: true
      categories_url_format: "category/{file}"
      pagination_per_page: 10
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      pagination_keep_content: true
      draft: true
      draft_on_serve: false
      draft_if_future_date: true

extra:
  Can1425:
    name: W-Can1425
    web: https://can1425.flowecho.org/
    github: https://github.com/Can1425/
  LP:
    name: LP_OVER
    web: /
    github: https://github.com/LP_OVER/
  Gxxk:
    name: Gxxk
    web: /
    github: https://github.com/Gxxk_/
  yishang:
    name: 我叫以赏
    web: https://lovepikachu.top/
    github: https://github.com/wojiaoyishang/
  CycleBai:
    name: Cycle Bai
    web: /
    github: https://github.com/CycleBai/
  HowardJones:
    name: Howard Jones
    web: /
    github: https://github.com/HowardJoness/
  emofalling:
    name: emofalling
    web: /
    github: https://github.com/emofalling

nav:
  - 主页:
      - index.md
  - 博客:
      - blog/index.md
  - 知识库:
      - wiki/index.md
  - 历史资料:
      - history/index.md
  - 讨论:
      - discussion/index.md