name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install packages
        run: "uv sync"

      - name: Build
        run: "uv run mkdocs build"

      - name: Copy files
        run: "mv scripts/main.ts site/main.ts"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "victorzhang-flowecho-wa-74"
          entrypoint: "site/main.ts"
          root: ""
          
          
